pipeline {
    agent none
    stages {
        stage('mvn build') {
            agent { docker 'maven:3.3.3' }
            steps {
                sh 'mvn --version'
            }
        }
        stage('node build') {
            agent { docker 'node:7-alpine' }
            steps {
                sh 'node --version'
            }
        }
    }
}
